"""Domain models for Tracer."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum


class Sector(str, Enum):
    TECHNOLOGY = "technology"
    HEALTHCARE = "healthcare"
    FINANCIALS = "financials"
    ENERGY = "energy"
    MATERIALS = "materials"
    INDUSTRIALS = "industrials"
    CONSUMER_DISCRETIONARY = "consumer_discretionary"
    CONSUMER_STAPLES = "consumer_staples"
    UTILITIES = "utilities"
    REAL_ESTATE = "real_estate"
    COMMUNICATION_SERVICES = "communication_services"


class Region(str, Enum):
    US = "us"
    EU = "eu"
    ASIA = "asia"
    EMERGING = "emerging"
    GLOBAL = "global"


class SignalDirection(str, Enum):
    LONG = "long"
    SHORT = "short"
    NEUTRAL = "neutral"


@dataclass(frozen=True)
class Stock:
    """A tradeable security."""

    ticker: str
    name: str
    sector: Sector | None = None
    region: Region = Region.US
    market_cap: float | None = None
    currency: str = "USD"


@dataclass
class Signal:
    """A trading signal generated by the pipeline."""

    ticker: str
    direction: SignalDirection
    conviction: float  # 0.0 - 10.0
    thesis: str
    evidence: list[str] = field(default_factory=list)
    contrarian_angle: str | None = None
    risk_factors: list[str] = field(default_factory=list)
    time_horizon_days: int | None = None
    generated_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self) -> None:
        if not 0.0 <= self.conviction <= 10.0:
            raise ValueError(f"Conviction must be between 0.0 and 10.0, got {self.conviction}")


@dataclass
class Report:
    """An alpha report produced at the end of the pipeline."""

    title: str
    ticker: str | None
    conviction: float
    what_happened: str
    evidence_chain: list[str]
    adversarial_check: list[str]
    verdict: str
    signals: list[Signal] = field(default_factory=list)
    generated_at: datetime = field(default_factory=datetime.now)


@dataclass
class TradeThesis:
    """A structured trade thesis generated by the pipeline (step 7)."""

    ticker: str
    entry_zone: tuple[float, float]  # (low, high) price range
    target_price: float
    stop_loss: float
    risk_reward_ratio: float  # (target - entry_mid) / (entry_mid - stop)
    catalyst: str  # what drives the move
    catalyst_date: str | None  # expected timing (e.g. 'Q2 2026', '2026-05-01')
    conviction: int  # 1-10 score
    summary: str  # one-paragraph thesis

    def __post_init__(self) -> None:
        if not 1 <= self.conviction <= 10:
            raise ValueError(f"Conviction must be between 1 and 10, got {self.conviction}")


@dataclass
class ToolResult:
    """Uniform result contract for all pipeline tools.

    All pipeline tools return this type, consumed by the AnalysisLoop.
    Failed tools are excluded from the evidence chain and flagged in the response caveat.
    """

    tool: str
    success: bool
    data: dict
    source: str
    fetched_at: datetime = field(default_factory=datetime.now)
    is_stale: bool = False
    error: str | None = None
