"""Conversation layer constants — stopwords, sectors, keywords, and pronouns.

Separated from context.py for readability.  These are used by the context
extraction and pronoun resolution logic.
"""

from __future__ import annotations

import re

# Uppercase 1-5 letter words that look like tickers.
TICKER_RE = re.compile(r"\b([A-Z]{1,5})\b")

# Common English words that match the ticker pattern but aren't tickers.
TICKER_STOPWORDS = frozenset(
    {
        "I",
        "A",
        "AM",
        "AN",
        "AS",
        "AT",
        "BE",
        "BY",
        "DO",
        "GO",
        "HE",
        "IF",
        "IN",
        "IS",
        "IT",
        "ME",
        "MY",
        "NO",
        "OF",
        "OK",
        "ON",
        "OR",
        "SO",
        "TO",
        "UP",
        "US",
        "WE",
        "AND",
        "ARE",
        "BUT",
        "CAN",
        "DID",
        "FOR",
        "GET",
        "GOT",
        "HAS",
        "HAD",
        "HER",
        "HIM",
        "HIS",
        "HOW",
        "ITS",
        "LET",
        "MAY",
        "NOT",
        "NOW",
        "OLD",
        "OUR",
        "OWN",
        "SAY",
        "SHE",
        "THE",
        "TOO",
        "TRY",
        "USE",
        "WAY",
        "WHO",
        "WHY",
        "YOU",
        "ALL",
        "ANY",
        "DAY",
        "FEW",
        "NEW",
        "BUY",
        "SELL",
        "ALSO",
        "BACK",
        "BEEN",
        "CALL",
        "COME",
        "EACH",
        "FIND",
        "FROM",
        "GIVE",
        "GOOD",
        "HAVE",
        "HERE",
        "HIGH",
        "JUST",
        "KNOW",
        "LAST",
        "LIKE",
        "LONG",
        "LOOK",
        "MADE",
        "MAKE",
        "MORE",
        "MOST",
        "MUCH",
        "MUST",
        "NAME",
        "ONLY",
        "OVER",
        "PART",
        "SAME",
        "SHOW",
        "SOME",
        "SUCH",
        "TAKE",
        "TELL",
        "THAN",
        "THAT",
        "THEM",
        "THEN",
        "THEY",
        "THIS",
        "TIME",
        "VERY",
        "WANT",
        "WELL",
        "WERE",
        "WHAT",
        "WHEN",
        "WILL",
        "WITH",
        "WORK",
        "YEAR",
        "YOUR",
        "DEEP",
        "ABOUT",
        "AFTER",
        "BEING",
        "COULD",
        "EVERY",
        "FIRST",
        "GREAT",
        "NEVER",
        "OTHER",
        "PLACE",
        "POINT",
        "RIGHT",
        "SHALL",
        "SINCE",
        "SMALL",
        "STILL",
        "THEIR",
        "THERE",
        "THESE",
        "THING",
        "THINK",
        "THOSE",
        "THREE",
        "UNDER",
        "WHERE",
        "WHICH",
        "WHILE",
        "WORLD",
        "WOULD",
        "QUICK",
        "BRIEF",
    }
)

SECTORS = frozenset(
    {
        "semiconductor",
        "tech",
        "technology",
        "energy",
        "finance",
        "financial",
        "healthcare",
        "biotech",
        "retail",
        "automotive",
        "ev",
        "battery",
        "ai",
        "cloud",
        "crypto",
        "real estate",
        "defense",
        "telecom",
        "media",
        "consumer",
        "industrial",
        "materials",
        "utilities",
    }
)

INTENT_KEYWORDS: dict[str, list[str]] = {
    "buy": ["buy", "long", "entry", "accumulate", "purchase"],
    "sell": ["sell", "short", "exit", "dump", "liquidate"],
    "research": ["analyze", "analysis", "research", "investigate", "look into", "tell me about"],
    "monitor": ["monitor", "watch", "track", "alert", "notify"],
}

DEPTH_QUICK = {"quick", "brief", "summary", "briefly", "short", "overview", "glance"}
DEPTH_DEEP = {"analyze", "detail", "detailed", "deep", "thorough", "comprehensive", "full"}

# Pronouns that resolve to current or previous topic.
CURRENT_PRONOUNS = {"this", "it", "this stock", "이거", "이것"}
PREVIOUS_PRONOUNS = {"previous", "previous one", "전에 본 것"}
ANOTHER_PRONOUNS = {"another", "another one", "something else", "다른 거"}

MAX_TOPIC_STACK = 5
DEFAULT_TURNS = 20
